# Generated by Django 4.0.5 on 2022-06-18 20:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=60)),
                ('police_number', models.IntegerField(blank=True, null=True)),
                ('health_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
