# Generated by Django 4.0.5 on 2022-06-18 22:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(max_length=60)),
                ('police_number', models.IntegerField(blank=True, null=True)),
                ('health_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hood.neighborhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.profile'),
        ),
    ]
