# Generated by Django 4.0.5 on 2023-07-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='hood.neighbourhood'),
        ),
    ]
