# Generated by Django 4.0.5 on 2022-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neighborhood',
            new_name='Neighbourhood',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
    ]
